id: d1105cf7-6e55-479f-a5d9-14fd6d02b051
name: ""
links:
  website: https://www.btrust.tech/
  twitter: https://x.com/btrustteam
category: Education
original_language: en
tags:
  - development
  - software
  - decentralization
